### ISSUE TITLE
My Rewards: Rearrange the buttons

### ISSUE THREAD

**Issue by Pol-Lanski** [GeneralMagicio/dappnode-mev-smoothing-pool#63]
Tests with our initial users tell us that this section is confusing. 
After some bouncing of ideas, they suggested that Claimable should be at the top, followed by the button "Claim" 

Then the pending, and at the bottom "Total accumulated".

<img width="273" alt="Screenshot 2023-05-11 at 11 51 28" src="https://github.com/GeneralMagicio/dappnode-mev-smoothing-pool/assets/19168735/101f0700-04c3-4b7b-81a0-fccbed315d8d">

And doing a review of the copy and tooltips:
* Claimable ✅  - Tooltip: "Rewards ready to be claimed from all your validators"
* Total accumulated ➡️ change to ➡️ Lifetime earned. - Tooltip: "Claimable now + already claimed in the past"
* Pending  ✅  - Tooltip "Non-confirmed rewards that will become claimable after proposing a block".

Also, please change the number of pending to Green (@tosin can you provide a hex?)  and with a + at the front.
<img width="186" alt="Screenshot 2023-05-11 at 13 29 47" src="https://github.com/GeneralMagicio/dappnode-mev-smoothing-pool/assets/19168735/59f41763-3ee5-45b7-bea1-e8129c63fbe3">

**Comment by marthendalnunes** [comment]
@Pol-Lanski changes applied, check the preview deploy https://dappnode-mev-smoothing-pool-git-marthendal-c049a1-general-magic.vercel.app/
