### ISSUE TITLE
Update warning column depending on the validator state

### ISSUE THREAD

**Issue by alrevuelta** [GeneralMagicio/dappnode-mev-smoothing-pool#68]
The "warning" column should display an indicator of the following states. Just an emoji would be enough:
* "yellowcard": 🟡
* "redcard": 🔴
* "banned": 💀

<img width="844" alt="image" src="https://github.com/GeneralMagicio/dappnode-mev-smoothing-pool/assets/8811422/6a3aaa97-0115-45ea-93e8-694c91f87400">

added: see below

**Comment by alrevuelta** [comment]
![image](https://github.com/GeneralMagicio/dappnode-mev-smoothing-pool/assets/8811422/14d86e28-e530-4223-9e9f-dad344275a2c)

one last thing before closing this. A banned validator shouldnt be able to Subscribe again. So the subscribe button should be disabled or not present.

**Comment by mateodaza** [comment]
Fixed and merged [here](https://github.com/GeneralMagicio/dappnode-mev-smoothing-pool/pull/82)
